= Кодекс поведения участника

== Наши обязательства

Мы, как участники, авторы, администраторы, модераторы и лидеры обязуемся сделать участие в сообществе свободным от притеснений для всех, независимо от возраста, телосложения, видимых или невидимых ограничений способности, этнической принадлежности, половых признаков, гендерной идентичности и выражения, уровня опыта, образования, социо-экономического статуса, национальности, внешности, расы, религии, или сексуальной идентичности и ориентации.

Мы обещаем действовать и взаимодействовать таким образом, чтобы вносить вклад в открытое, дружелюбное, многообразное, инклюзивное и здоровое сообщество.

== Наши стандарты

Примеры поведения, создающие условия для благоприятных взаимоотношений включают в себя:

* Проявление доброты и эмпатии к другим участникам проекта
* Уважение к чужой точке зрения и опыту
* Конструктивная критика и принятие конструктивной критики
* Принятие ответственности, принесение извинений тем, кто пострадал от наших ошибок и извлечение уроков из опыта
* Ориентирование на то, что лучше подходит для сообщества, а не только для нас лично

Примеры неприемлемого поведения участников включают в себя:

* Использование выражений или изображений сексуального характера и нежелательное сексуальное внимание или домогательство в любой форме
* Троллинг, оскорбительные или уничижительные комментарии, переход на личности или затрагивание политических убеждений
* Проявление агрессии или неприязни к другим участникам сообщества
* Публикация личной информации других лиц, например, физического или электронного адреса, без явного разрешения
* Иное поведение, которое обоснованно считать неуместным в профессиональной обстановке

== Обязанности

Лидеры сообщества отвечают за разъяснение и применение наших стандартов приемлемого поведения и будут предпринимать соответствующие и честные меры по исправлению положения в ответ на любое поведение, которое они сочтут неприемлемым, угрожающим, оскорбительным или вредным.

Лидеры сообщества обладают правом и обязанностью удалять, редактировать или отклонять сообщения и комментарии, код, вопросы и другой вклад, который не совпадает с кодексом поведения, и предоставят причины принятого решения, когда сочтут нужным.

== Область применения

Данный кодекс поведения применим во всех во всех публичных физических и цифровых пространства сообщества, а также когда человек официально представляет сообщество в публичных местах.
Примеры представления проекта или сообщества включают использование электронной почты сообщества, публикации в аккаунте сообщества в социальных сетях или мессенджерах, или упоминания как представителя в онлайн или оффлайн мероприятии.

== Приведение в исполнение

О случаях неприемлемого поведения можно сообщить ответственным лидерам сообщества с помощью контактов, указанных в описании https://t.me/jprof_by[чата сообщества].
Все жалобы будут рассмотрены и расследованы оперативно и беспристрастно.

Все лидеры сообщества обязаны уважать неприкосновенность частной жизни и личную неприкосновенность автора сообщения.

== Руководство по исполнению

Лидеры сообщества будут следовать следующим принципам воздействия в сообществе, чтобы определить последствия для тех, кого они считают виновными в нарушении данного кодекса поведения:

=== 1. Предупреждение

**Общественное влияние**: Использование недопустимой лексики или другое поведение, считающиеся непрофессиональным или нежелательным в сообществе.

**Последствия**: Личное или публичное письменное предупреждение от лидеров сообщества, объясняющее суть нарушения и причины нежелательности подобного поведения.

=== 2. Временный бан

**Общественное влияние**: Серьёзное нарушение стандартов сообщества, включая продолжительное неуместное поведение.

**Последствия**: Временный запрет (бан) на любое взаимодействие или публичное общение в сообществе на определенный период времени.
На этот период не допускается публичное взаимодействие с сообществом людей, вовлеченных в инцидент, включая незапрошенное взаимодействие с теми, кто обеспечивает соблюдение кодекса.
Нарушение этих правил влечет за собой вечный бан.

=== 3. Вечный бан

**Общественное влияние**: Демонстрация систематических нарушений стандартов сообщества, включая продолжающееся неуместное поведение.

**Последствия**: Вечный запрет на любое публичное взаимодействие с сообществом.

== Атрибуция

Данный кодекс поведения основан на кодекс поведения участника, версии 2.0, доступной по адресу https://www.contributor-covenant.org/version/2/0/code_of_conduct.html.

Принципы Воздействия в Сообществе были вдохновлены link:https://github.com/mozilla/diversity[Mozilla's code of conduct enforcement ladder].
